### ISSUE TITLE
In case of FG-SBIR, what is ShoeV2_coordinate mentioned in dataset.py?

### ISSUE THREAD

**Issue by aisagarw** [aneeshan95/StyleMeUp#1]

**Comment by aisagarw** [comment]
In case of FG-SBIR, what is ShoeV2_coordinate mentioned in dataset.py?

**Comment by aneeshan95** [comment]
It is a file storing the co-ordinate information of sketch-strokes for each sketch in the format (x, y, k) where _x_ and _y_ are axes coordinates and _k_ represents pen-state (0 = down ; 1 = up). Using this representation, the sketches can be rendered as a black line-drawing on a white canvas in image format.
